CREATE TABLE `examination` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `childid` int(10) unsigned DEFAULT '0' COMMENT '关联儿童',
  `field1` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '儿童姓名',
  `field2` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '实足年龄_岁',
  `field3` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '实足年龄_月',
  `field4` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '体检日期',
  `field5` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '年龄别体重评价',
  `field6` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '年龄别身长评价',
  `field7` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '身长别体重评价',
  `field8` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '体检医生签名',
  `field9` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '体检机构',
  `field10` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '腹部',
  `field11` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '腹部异常信息',
  `field12` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '贫血评价',
  `field13` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '佝偻病评价',
  `field14` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '佝偻病活动期',
  `field15` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '营养不良评价',
  `field16` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '肥胖评价（依肥胖度划分）',
  `field17` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '肥胖评价（标准差五分法）',
  `field18` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '健康评价_其他',
  `field19` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '出生日期',
  `field20` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT 'BMI值',
  `field21` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '24小时母乳喂养',
  `field22` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '前囟',
  `field23` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '面色',
  `field24` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '矫治颗数',
  `field25` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '两次随访间患病情况',
  `field26` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '耳外观',
  `field27` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '耳外观异常信息',
  `field28` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '眼外观',
  `field29` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '眼外观异常信息',
  `field30` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '步态',
  `field31` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '步态异常信息',
  `field32` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '性别',
  `field33` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '肛门/外生殖器',
  `field34` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '肛门/外生殖器异常信息',
  `field35` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '发育评估',
  `field36` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '指导内容',
  `field37` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '先天性心脏病可疑征象',
  `field38` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '心脏',
  `field39` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '先天性心脏病可疑征象阳性内容',
  `field40` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '身长（cm）',
  `field41` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '血红蛋白值',
  `field42` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '先天性髋关节脱位可疑征象',
  `field43` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '发育性髋关节发育不良可疑征象阳性内容',
  `field44` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '四肢',
  `field45` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '四肢异常信息',
  `field46` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '肺脏',
  `field47` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '肺脏异常信息',
  `field48` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '口腔',
  `field49` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '口腔异常信息',
  `field50` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '脐部',
  `field51` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '脐部异常信息',
  `field52` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '下次体检日期',
  `field53` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '肥胖度评价',
  `field54` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '户外活动（小时/日）',
  `field55` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '经皮测氧饱和度',
  `field56` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '经皮测氧饱和度异常_右手',
  `field57` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '经皮测氧饱和度异常_足',
  `field58` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '体格检查_其他',
  `field59` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '转诊建议',
  `field60` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '转诊原因',
  `field61` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '转诊机构及科室',
  `field62` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '佝偻病体征',
  `field63` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '佝偻病症状',
  `field64` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '新生儿产科听力筛查情况',
  `field65` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '皮肤',
  `field66` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '皮肤异常信息',
  `field67` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '服用铁剂情况',
  `field68` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '出牙数（颗）',
  `field69` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '服用维生素D',
  `field70` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '体重（kg）',
  `field71` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '听力筛查',
  `field72` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '左耳听力',
  `field73` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '右耳听力',
  `field74` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT 'OAE耳声发射请选择',
  `field75` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '扁桃体',
  `field76` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '沙眼',
  `field77` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '视力左',
  `field78` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '视力右',
  `field79` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '心脏异常',
  `field80` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '头围',
  `field81` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '听力筛查方法',
  `field82` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '本次体检属于',
  `field83` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '体检费用',
  `field84` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '龋齿颗数',
  `field85` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '户口',
  `field86` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '发放中医药健康指导宣传材料',
  `field87` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '发放年龄',
  `field88` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '使用国家母子健康手册',
  `field89` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '预警征象',
  `field90` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '预警征象描述',
  `field91` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '心理行为问题',
  `field92` varchar(30) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '心理行为问题描述',
  `source` int(11) NOT NULL DEFAULT '0',
  `isupdate` tinyint(4) NOT NULL DEFAULT '0',
  `createtime` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_childid` (`childid`),
  KEY `idx_isupdate` (`isupdate`),
  KEY `idx_birthday` (`field19`),
  KEY `idx_field52` (`field52`(7)) USING BTREE,
  KEY `idx_source` (`source`)
)