<?php
/**
 * Created by PhpStorm.
 * User: wangzhen
 * Date: 2017/12/26
 * Time: 下午3:16
 */

namespace weixin\controllers;


class Controller extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if(\Yii::$app->request->get('we')=="new")
        {
            $cookies = \Yii::$app->response->cookies;
            $cookies->add(new \yii\web\Cookie([
                'name' => 'we',
                'value' => 'new',
            ]));
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}