<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "access".
 *
 * @property int $id
 * @property int $type 类型
 * @property int $createtime 创建时间
 * @property int $long 时长
 * @property int $cid 备份ID
 * @property int $userid 用户
 */
class Access extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'access';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['type', 'createtime', 'long', 'cid', 'userid'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'createtime' => 'Createtime',
            'long' => 'Long',
            'cid' => 'Cid',
            'userid' => 'Userid',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
