<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "appoint_calling_list".
 *
 * @property int $id
 * @property int $aid
 * @property int $acid
 * @property string $openid
 * @property int $createtime
 * @property int $state
 */
class AppointCallingList extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'appoint_calling_list';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['aid', 'acid', 'createtime', 'state'], 'integer'],
            [['openid'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'aid' => 'Aid',
            'acid' => 'Acid',
            'openid' => 'Openid',
            'createtime' => 'Createtime',
            'state' => 'State',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
