<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "appoint_hpv_setting".
 *
 * @property int $id
 * @property int $doctorid 社区
 * @property int $week1 周一
 * @property int $week2 周二
 * @property int $week3 周三
 * @property int $week4 周四
 * @property int $week5 周五
 * @property int $createtime
 */
class AppointHpvSetting extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'appoint_hpv_setting';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['doctorid', 'week1', 'week2', 'week3', 'week4', 'week5', 'createtime'], 'integer'],
            [['week1', 'week2', 'week3', 'week4', 'week5'], 'required'],
            [['vid'],'safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'doctorid' => '社区',
            'week1' => '周一',
            'week2' => '周二',
            'week3' => '周三',
            'week4' => '周四',
            'week5' => '周五',
            'vid' => '选择疫苗',

            'createtime' => 'Createtime',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        if(is_array($this->vid)){
            $this->vid = implode(',',$this->vid);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
