<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "article_category".
 *
 * @property int $id
 * @property string $name
 * @property int $pid
 * @property string $pids
 * @property int $createtime
 * @property int $level
 */
class ArticleCategory extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'article_category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['pid', 'createtime', 'level'], 'integer'],
            [['name', 'pids'], 'string', 'max' => 20],
            ['pid', 'default', 'value' => 0]

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '名称',
            'pid' => '父类',
            'pids' => '父类集',
            'createtime' => '创建时间',
            'level' => '数据状态',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert)
        {
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
