<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "article_like".
 *
 * @property int $id
 * @property int $artid
 * @property int $userid
 * @property int $createtime
 */
class ArticleLike extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article_like';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['artid', 'userid', 'createtime'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'artid' => 'Artid',
            'userid' => 'Userid',
            'createtime' => 'Createtime',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
