<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "article_push_vaccine".
 *
 * @property int $id
 * @property int $aid
 * @property string $openid
 * @property int $createtime
 * @property int $state
 * @property int $level
 */
class ArticlePushVaccine extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'article_push_vaccine';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['aid', 'createtime', 'state', 'level'], 'integer'],
            [['openid'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'aid' => 'Aid',
            'openid' => 'Openid',
            'createtime' => 'Createtime',
            'state' => 'State',
            'level' => 'Level',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
