<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "article_comment".
 *
 * @property int $id
 * @property string $content 内容
 * @property int $userid 评论人
 * @property int $createtime 评论时间
 * @property int $artid 文章id
 */
class ArticleComment extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article_comment';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'content', 'userid', 'artid'], 'required'],
            [['id', 'userid', 'createtime', 'artid'], 'integer'],
            [['content'], 'string', 'max' => 200],
            [['id'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'content' => '内容',
            'userid' => '评论人',
            'createtime' => '评论时间',
            'artid' => '文章id',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
