<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "ask_chat_room".
 *
 * @property int $id
 * @property int $userid 用户
 * @property int $doctorid 回复医生
 * @property int $createtime 创建时间
 * @property int $orderid 关联订单
 */
class AskChatRoom extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ask_chat_room';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userid', 'doctorid', 'createtime', 'orderid'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userid' => '用户',
            'doctorid' => '回复医生',
            'createtime' => '创建时间',
            'orderid' => '关联订单',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public static function createRoom($orderid,$userid=0,$doctorid=0){
        $room=AskChatRoom::findOne(['orderid'=>$orderid]);
        if(!$room){
            $room=new AskChatRoom();
            $room->orderid=$orderid;
            $room->userid=$userid;
            $room->doctorid=$doctorid;
            $room->save();
        }
        return $room;
    }
}
