<?php

namespace common\models;

use hospital\models\user\UserDoctor;
use Yii;

/**
 * This is the model class for table "autograph".
 *
 * @property int $id
 * @property int $createtime
 * @property int $endtime
 * @property int $starttime
 * @property string $img
 * @property int $loginid
 * @property int $userid
 * @property int $doctorid
 */
class Autograph extends \yii\db\ActiveRecord
{
    public  static function find()
    {
        $find=parent::find();
        $find->andWhere(['level'=>1]);
        return $find;
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'autograph';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['createtime', 'loginid','userid','doctorid','endtime','starttime','level'], 'integer'],
            [['img'], 'string', 'max' => 150],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'createtime' => '签约时间',
            'endtime' => '有效截止日期',
            'img' => '签名',
            'userid' => '用户',
            'doctorid'=>'社区医院ID'
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
            $this->starttime=date('Ymd');
            $this->endtime=date('Ymd',strtotime('+1 year'));
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
