<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%carousel}}".
 *
 * @property string $id
 * @property string $url 链接地址
 * @property string $img 图片地址
 * @property int $sort 排序
 * @property int $type 类型
 * @property int $name 名称

 * @property int $atype 类型
 * @property int $state 类型
 * @property string $createtime 创建时间
 */
class Carousel extends \yii\db\ActiveRecord
{
    public static $typeText=[1=>'育儿课堂'];
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%carousel}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sort', 'type', 'createtime','atype'], 'integer'],
            [['url', 'img'], 'string', 'max' => 100],
            [['name'], 'string', 'max' => 20],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'url' => '链接地址',
            'img' => '图片地址',
            'name' => '名称',

            'sort' => '排序',
            'type' => '类型',
            'atype' => '广告类型',
            'state' => '状态',
            'createtime' => '创建时间',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert)
        {
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
