<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "chain".
 *
 * @property string $id
 * @property string $url 链接地址
 * @property string $title 说明
 * @property string $createtime 创建时间
 */
class Chain extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'chain';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['createtime'], 'integer'],
            [['url'], 'string', 'max' => 255],
            [['title'], 'string', 'max' => 20],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'url' => '链接地址',
            'title' => '说明',
            'createtime' => '创建时间',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert)
        {
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
