<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "chat_record".
 *
 * @property integer $id
 * @property integer $userid
 * @property integer $touserid
 * @property integer $read
 * @property integer $createtime
 */
class ChatRecord extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'chat_record';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'userid', 'touserid', 'createtime'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '主键',
            'userid' => '发送用户',
            'touserid' => '接受用户',
            'createtime' => '创建时间',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert)
        {
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
