<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "clock_in".
 *
 * @property int $id
 * @property int $userid 用户
 * @property int $createtime 时间
 * @property int $datetime 日期
 * @property int $day 连续
 */
class ClockIn extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'clock_in';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userid', 'createtime', 'datetime', 'day'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userid' => '用户',
            'createtime' => '时间',
            'datetime' => '日期',
            'day' => '连续',
        ];
    }

    public function action($userid){

        $clockInToday=self::find()->where(['userid'=>$userid])
            ->andWhere(['datetime'=>date('Ymd')])
            ->one();
        if($clockInToday){
            return 20010;
        }

        $clockIn=self::find()->where(['userid'=>$userid])
            ->andWhere(['datetime'=>date('Ymd',strtotime('-1 day'))])
            ->one();
        $point=new Points();

        if($clockIn){
            $day=$clockIn->day+1;
            $p=$clockIn->day%7+1;
            $point->addPoint($userid,5,0,$p);

        }else{
            $day=1;
            $point->addPoint($userid,5);

        }
        $this->userid=$userid;
        $this->day=$day;
        $this->save();
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
            $this->datetime=date('Ymd');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }}
