<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "data_user".
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property integer $type
 * @property integer $hospital
 * @property integer $province
 * @property integer $county
 * @property integer $city
 * @property integer $createtime
 * @property integer $lasttime
 */
class DataUser extends \yii\db\ActiveRecord
{
    public static $typeText=[1=>'政府',2=>'地区',3=>'医院'];
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'data_user';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password'], 'required'],
            [['type', 'hospital', 'province', 'county', 'city', 'createtime', 'lasttime'], 'integer'],
            [['username'], 'string', 'max' => 255],
            [['password'], 'string', 'max' => 32],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => '用户名',
            'password' => '密码',
            'type' => '类型',
            'hospital' => '医院ID',
            'province' => '省',
            'county' => '县',
            'city' => '市',
            'createtime' => '添加时间',
            'lasttime' => '最后一次登录时间',
        ];
    }

    public function beforeSave($insert){
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
