<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "doctor_parent_edit".
 *
 * @property int $id
 * @property int $doctorid 社区ID
 * @property int $userid 用户ID
 * @property int $childid 儿童ID
 * @property int $createtime
 * @property string $img 材料
 * @property int $teamid 医生团队ID
 * @property int $level 级别
 */
class DoctorParentEdit extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'doctor_parent_edit';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['doctorid', 'userid', 'childid', 'createtime', 'teamid', 'level'], 'integer'],
            [['img'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'doctorid' => '社区ID',
            'userid' => '用户ID',
            'childid' => '儿童ID',
            'createtime' => 'Createtime',
            'img' => '材料',
            'teamid' => '医生团队ID',
            'level' => '级别',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
