<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "doctors".
 *
 * @property int $userid 用户ID
 * @property string $name 姓名
 * @property int $sex 性别
 * @property int $age 年龄
 * @property int $birthday 生日
 * @property int $hospitalid 所以在医院
 * @property int $subject_b 一级科室
 * @property int $subject_s 二级科室
 * @property int $title 职称
 * @property string $intro 简介
 * @property string $avatar 头像
 * @property string $skilful 擅长
 * @property string $idnum 身份证号码
 * @property int $province 省
 * @property int $county 县
 * @property int $city 市
 * @property int $atitle 行政职称
 * @property int $otype 职业类型
 * @property string $authimg 证件照
 * @property string $type 医生类型
 */
class Doctors extends \yii\db\ActiveRecord
{
    public $phone;
    public static $sexText = [1 => '男', 2 => '女',];
    public static $titleText = [0 => '未设置', 1 => '主任医师', 2 => '副主任医师', 3 => '主治医师', 4 => '住院医师', 16 => '助理医师', 5 => '护士', 6 => '护师', 7 => '主管护师', 8 => '副主任护师', 9 => '主任护师', 10 => '药士', 11 => '药师', 12 => '主管药师', 13 => '副主任药师', 14 => '主任药师', 15 => '其他', 17 => '检验士', 18 => '主管检验师', 19 => '副主任检验师', 20 => '主任检验师'];
    public static $typeText = [0 => '普通', 1 => '社区医生'];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'doctors';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userid', 'phone'], 'required'],
            [['phone', 'userid', 'sex', 'age', 'birthday', 'hospitalid', 'subject_b', 'subject_s', 'title', 'province', 'county', 'city', 'atitle', 'otype'], 'integer'],
            [['name'], 'string', 'max' => 15],
            [['intro', 'avatar', 'skilful'], 'string', 'max' => 150],
            [['idnum'], 'string', 'max' => 18],
            [['authimg', 'type'], 'string', 'max' => 200],
            [['userid'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'userid' => '用户ID',
            'name' => '姓名',
            'sex' => '性别',
            'age' => '年龄',
            'birthday' => '生日',
            'hospitalid' => '所以在医院',
            'subject_b' => '一级科室',
            'subject_s' => '二级科室',
            'title' => '职称',
            'intro' => '简介',
            'avatar' => '头像',
            'skilful' => '擅长',
            'idnum' => '身份证号码',
            'province' => '省',
            'county' => '县',
            'city' => '市',
            'atitle' => '行政职称',
            'otype' => '职业类型',
            'authimg' => '证件照',
            'type' => '医生类型',
            'phone' => '手机号',

        ];
    }

    public function beforeSave($insert)
    {
        $user = new User();
        $user->phone = $this->phone;
        $user->type = 3;
        if ($user->save()) {
            $this->userid = $user->id;
        } else {
            $this->addError('userid', implode(',', $user->firstErrors));
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
