<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "doctor_hospital".
 *
 * @property int $id
 * @property int $doctorid
 * @property int $hospitalid
 * @property int $createtime
 */
class DoctorHospital extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'doctor_hospital';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['doctorid', 'hospitalid'], 'required'],
            [['doctorid', 'hospitalid', 'createtime'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'doctorid' => 'Doctorid',
            'hospitalid' => '所属社区',
            'createtime' => 'Createtime',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
