<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "doctor_parent_edit".
 *
 * @property int $id
 * @property int $doctorid 社区ID
 * @property int $userid 用户ID
 * @property int $childid 儿童ID
 * @property int $createtime
 * @property string $img 材料
 * @property int $teamid 医生团队ID
 * @property int $level 级别
 * @property int $undoctorid 现社区
 */
class DoctorParentEdit extends \yii\db\ActiveRecord
{
    public static $levelText=[0=>'未处理',1=>'已处理',2=>'已驳回'];
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'doctor_parent_edit';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['doctorid', 'userid', 'childid', 'createtime', 'teamid', 'level','undoctorid'], 'integer'],
            [['img'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'doctorid' => '目标社区',
            'userid' => '用户ID',
            'childid' => '儿童ID',
            'createtime' => 'Createtime',
            'img' => '材料',
            'teamid' => '医生团队ID',
            'level' => '级别',
            'undoctorid'=>'原社区'
        ];
    }
    public function beforeSave($insert)
    {
        $doctorParent=DoctorParent::findOne(['parentid'=>$this->userid]);

        if($insert){
            $this->createtime=time();
            $this->undoctorid=$doctorParent->doctorid;
        }elseif($this->level==2 && ($doctorParent->doctorid!=$this->doctorid)){
            $doctorParent->doctorid=$this->doctorid;
            $doctorParent->save();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
