<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "exa_notice_setup".
 *
 * @property int $id
 * @property int $hospitalid 社区ID
 * @property int $level 是否启用
 * @property int $end 结束提醒
 * @property int $month1 2-3月
 * @property int $month2 5-6月
 * @property int $month3 8-9月
 * @property int $month4 11-12月
 * @property int $month5 1岁半
 * @property int $month6 2岁
 * @property int $month7 2岁半
 * @property int $month8 3岁
 */
class ExaNoticeSetup extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'exa_notice_setup';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['hospitalid', 'level', 'end', 'month1', 'month2', 'month3', 'month4', 'month5', 'month6', 'month7', 'month8'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'hospitalid' => '社区ID',
            'level' => '启用',
            'end' => '到期提醒',
            'month1' => '2-3月',
            'month2' => '5-6月',
            'month3' => '8-9月',
            'month4' => '11-12月',
            'month5' => '1岁半',
            'month6' => '2岁',
            'month7' => '2岁半',
            'month8' => '3岁',
        ];
    }

    public function beforeSave($insert)
    {
        $fields=self::fields();
        foreach($fields as $k=>$v){

            if(!$this->$v && $v!='id'){
                $this->$v=0;
            }
        }


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
