<?php
/**
 * 家庭医生服务项目
 */

namespace common\models;


class FamilyDoctorServices
{
    static public $typeText=[1=>'宣教',2=>'接种',3=>'体检'];
    static public $init=[
        [
            'title'=>'1月',
            'services'=>[
                [
                    'name'=>'满月中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'乙肝疫苗接种',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'2月',
            'services'=>[
                [
                    'name'=>'脊灰疫苗',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'3月',
            'services'=>[
                [
                    'name'=>'3月龄中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'3月龄体检',
                    'type'=>3,
                ],
                [
                    'name'=>'百白破疫苗',
                    'type'=>2,
                ],
                [
                    'name'=>'脊灰疫苗',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'4月',
            'services'=>[
                [
                    'name'=>'百白破第二剂',
                    'type'=>2,
                ],
                [
                    'name'=>'脊灰疫苗opv',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'5月',
            'services'=>[
                [
                    'name'=>'百白破第三剂',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'6月',
            'services'=>[
                [
                    'name'=>'6月龄中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'6月龄体检',
                    'type'=>3,
                ],
                [
                    'name'=>'A群流脑疫苗',
                    'type'=>2,
                ],
                [
                    'name'=>'乙肝第三剂',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'8月',
            'services'=>[
                [
                    'name'=>'8月龄中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'8月龄体检',
                    'type'=>3,
                ],
                [
                    'name'=>'麻风腮疫苗',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'9月',
            'services'=>[
                [
                    'name'=>'A群流脑疫苗',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'1岁',
            'services'=>[
                [
                    'name'=>'1岁中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'1周岁体检',
                    'type'=>3,
                ],
                [
                    'name'=>'乙脑减毒疫苗',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'1岁半',
            'services'=>[
                [
                    'name'=>'一半岁中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'一岁半体检',
                    'type'=>3,
                ],
                [
                    'name'=>'麻腮风疫苗',
                    'type'=>2,
                ],
                [
                    'name'=>'百白破第四剂',
                    'type'=>2,
                ],
                [
                    'name'=>'甲肝疫苗',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'2岁',
            'services'=>[
                [
                    'name'=>'两岁中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'两岁体检',
                    'type'=>3,
                ],
                [
                    'name'=>'乙脑减毒疫苗',
                    'type'=>2,
                ],
                [
                    'name'=>'甲肝第二剂',
                    'type'=>2,
                ],

            ],
        ],
        [
            'title'=>'2岁半',
            'services'=>[
                [
                    'name'=>'两岁半中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'两岁半体检',
                    'type'=>3,
                ],
            ],
        ],
        [
            'title'=>'3岁',
            'services'=>[
                [
                    'name'=>'入托体检',
                    'type'=>2,
                ],
                [
                    'name'=>'三岁中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'三岁体检',
                    'type'=>2,
                ],
                [
                    'name'=>'A+C流脑疫苗',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'4岁',
            'services'=>[
                [
                    'name'=>'四岁中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'脊灰疫苗IPV',
                    'type'=>2,
                ],
                [
                    'name'=>'脊灰疫苗OPV',
                    'type'=>2,
                ],
            ],
        ],
        [
            'title'=>'5岁',
            'services'=>[
                [
                    'name'=>'五岁中医指导',
                    'type'=>1,
                ],
            ],
        ],
        [
            'title'=>'6岁',
            'services'=>[
                [
                    'name'=>'六岁中医指导',
                    'type'=>1,
                ],
                [
                    'name'=>'麻腮风第三剂',
                    'type'=>2,
                ],
                [
                    'name'=>'白破疫苗',
                    'type'=>2,
                ],
            ],
        ],



    ];

}