<?php
/**
 * 家庭医生服务项目
 */

namespace common\models;


class FamilyDoctorServices
{
    static public $typeText=[1=>'宣教',2=>'接种',3=>'体检'];
    static public $init=[
        [
            'title'=>'1月',
            'services'=>[
                [
                    'name'=>'满月中医指导',
                    'type'=>1,
                    'id'=>19,
                ],
                [
                    'name'=>'乙肝疫苗(第2剂)',
                    'type'=>2,
                    'id'=>1,
                ],
            ],
        ],
        [
            'title'=>'2月',
            'services'=>[
                [
                    'name'=>'脊灰疫苗(IPV)(第1剂)',
                    'type'=>2,
                    'id'=>4,
                ],
            ],
        ],
        [
            'title'=>'3月',
            'services'=>[
                [
                    'name'=>'3月龄中医指导',
                    'type'=>1,
                    'id'=>220,
                ],
                [
                    'name'=>'3月龄体检',
                    'type'=>3,
                    'id'=>1,
                ],
                [
                    'name'=>'无细胞百白破疫苗(第1剂)',
                    'type'=>2,
                    'id'=>6,
                ],
                [
                    'name'=>'脊灰疫苗(IPV)(第2剂)',
                    'type'=>2,
                    'id'=>5
                ],
            ],
        ],
        [
            'title'=>'4月',
            'services'=>[
                [
                    'name'=>'无细胞百白破疫苗(第2剂)',
                    'type'=>2,
                    'id'=>8
                ],
                [
                    'name'=>'脊灰疫苗(OPV)(第3剂)',
                    'type'=>2,
                    'id'=>7,
                ],
            ],
        ],
        [
            'title'=>'5月',
            'services'=>[
                [
                    'name'=>'无细胞百白破疫苗(第3剂)',
                    'type'=>2,
                    'id'=>9,
                ],
            ],
        ],
        [
            'title'=>'6月',
            'services'=>[
                [
                    'name'=>'6月龄中医指导',
                    'type'=>1,
                    'id'=>53,
                ],
                [
                    'name'=>'6月龄体检',
                    'type'=>3,
                    'id'=>2,
                ],
                [
                    'name'=>'A群流脑疫苗(第1剂)',
                    'type'=>2,
                    'id'=>11,
                ],
                [
                    'name'=>'乙肝疫苗(第3剂)',
                    'type'=>2,
                    'id'=>10,
                ],
            ],
        ],
        [
            'title'=>'8月',
            'services'=>[
                [
                    'name'=>'8月龄体检',
                    'type'=>3,
                    'id'=>3,
                ],
                [
                    'name'=>'麻风二联疫苗(第1剂)',
                    'type'=>2,
                    'id'=>12,
                ],
            ],
        ],
        [
            'title'=>'9月',
            'services'=>[
                [
                    'name'=>'A群流脑疫苗(第2剂)',
                    'type'=>2,
                    'id'=>14
                ],
            ],
        ],
        [
            'title'=>'1岁',
            'services'=>[
                [
                    'name'=>'1岁中医指导',
                    'type'=>1,
                    'id'=>54
                ],
                [
                    'name'=>'1周岁体检',
                    'type'=>3,
                ],
                [
                    'name'=>'乙脑减毒疫苗(第1剂)',
                    'type'=>2,
                    'id'=>13
                ],
            ],
        ],
        [
            'title'=>'1岁半',
            'services'=>[
                [
                    'name'=>'一半岁中医指导',
                    'type'=>1,
                    'id'=>55
                ],
                [
                    'name'=>'一岁半体检',
                    'type'=>3,
                ],
                [
                    'name'=>'麻腮风疫苗（第2剂）',
                    'type'=>2,
                    'id'=>21
                ],
                [
                    'name'=>'无细胞百白破疫苗(第4剂)',
                    'type'=>2,
                    'id'=>15,
                ],
                [
                    'name'=>'甲肝疫苗(第1剂)',
                    'type'=>2,
                    'id'=>17,
                ],
            ],
        ],
        [
            'title'=>'2岁',
            'services'=>[
                [
                    'name'=>'两岁中医指导',
                    'type'=>1,
                    'id'=>56

                ],
                [
                    'name'=>'两岁体检',
                    'type'=>3,
                ],
                [
                    'name'=>'乙脑减毒疫苗(第2剂)',
                    'type'=>2,
                    'id'=>18
                ],
                [
                    'name'=>'甲肝疫苗(第2剂)',
                    'type'=>2,
                    'id'=>17
                ],

            ],
        ],
        [
            'title'=>'2岁半',
            'services'=>[
                [
                    'name'=>'两岁半中医指导',
                    'type'=>1,
                    'id'=>57
                ],
                [
                    'name'=>'两岁半体检',
                    'type'=>3,
                ],
            ],
        ],
        [
            'title'=>'3岁',
            'services'=>[
                [
                    'name'=>'入托体检',
                    'type'=>2,
                ],
                [
                    'name'=>'三岁中医指导',
                    'type'=>1,
                    'id'=>58

                ],
                [
                    'name'=>'三岁体检',
                    'type'=>2,
                ],
                [
                    'name'=>'A+C群流脑疫苗(第1剂)',
                    'type'=>2,
                    'id'=>19,
                ],
            ],
        ],
        [
            'title'=>'4岁',
            'services'=>[
                [
                    'name'=>'四岁中医指导',
                    'type'=>1,
                    'id'=>122
                ],
                [
                    'name'=>'脊灰疫苗(IPV)(第4剂)',
                    'type'=>2,
                    'id'=>61
                ],
                [
                    'name'=>'脊灰疫苗(OPV)(第4剂)',
                    'type'=>2,
                    'id'=>20,
                ],
            ],
        ],
        [
            'title'=>'5岁',
            'services'=>[
                [
                    'name'=>'五岁中医指导',
                    'type'=>1,
                    'id'=>46

                ],
            ],
        ],
        [
            'title'=>'6岁',
            'services'=>[
                [
                    'name'=>'六岁中医指导',
                    'type'=>1,
                    'id'=>196,
                ],
                [
                    'name'=>'麻腮风疫苗(第3剂)',
                    'type'=>2,
                    'id'=>60,
                ],
                [
                    'name'=>'白破疫苗(DT)	',
                    'type'=>2,
                    'id'=>22,
                ],
            ],
        ],



    ];

}