<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "hospital_mail_show".
 *
 * @property int $id
 * @property int $mailid
 * @property int $hospitalid
 * @property int $createtime
 */
class HospitalMailShow extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'hospital_mail_show';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mailid', 'hospitalid', 'createtime'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mailid' => '通知ID',
            'hospitalid' => '社区ID',
            'createtime' => '查看时间',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
