<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "hospital_mail".
 *
 * @property int $id
 * @property string $content
 * @property int $touser
 * @property int $createtime
 * @property int $is_show
 */
class HospitalMail extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'hospital_mail';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['touser', 'createtime', 'is_show'], 'integer'],
            [['content'], 'string', 'max' => 200],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => '主键',
            'content' => '通知内容',
            'touser' => '接收用户',
            'createtime' => '创建时间',
            'is_show' => '读取状态',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
