<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "hospital_appoint".
 *
 * @property int $id
 * @property int $doctorid
 * @property int $cycle
 * @property int $delay
 * @property int type
 * @property int weeks
 */
class HospitalAppoint extends \yii\db\ActiveRecord
{
    public $week;
    public static $cycleText=[1=>'1周',2=>'2周',3=>'1个月'];
    public static $cycleNum=[1=>7,2=>14,3=>30];
    public static $typeText=[1=>'体检预约',2=>'疫苗预约',3=>'微量元素'];
    public static $intervalText=[1=>'一小时',2=>'半小时'];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'hospital_appoint';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cycle','delay','week'], 'required'],
            [['doctorid', 'cycle', 'delay','weeks','interval'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'doctorid' => 'Doctorid',
            'cycle' => 'Cycle',
            'delay' => 'Delay',
            'type' => 'Type',
            'weeks' => 'weeks',
            'interval'=>'预约时间段'

        ];
    }
    public function beforeSave($insert)
    {
        if($this->week){
            $this->weeks=implode('',$this->week);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
