<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "mother_article".
 *
 * @property int $id
 * @property string $title 标题
 * @property string $content 内容
 * @property string $createtime 创建时间
 * @property string $qcode 企业微信二维码
 */
class MotherArticle extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mother_article';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content'], 'required'],
            [['content'], 'string'],
            [['createtime'], 'safe'],
            [['title'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'content' => '内容',
            'createtime' => '创建时间',
            'qcode' => '企业微信二维码',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
