<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "push_log".
 *
 * @property int $id
 * @property int $type 类型
 * @property string $openid openid
 * @property int $createtime 时间
 * @property int $return 返回状态值
 */
class PushLog extends \yii\db\ActiveRecord
{
    public $typeText=[
        1=>'新关注用户福利通知'
    ];
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'push_log';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['type', 'openid', 'return'], 'required'],
            [['type', 'createtime', 'return','doctorid'], 'integer'],
            [['openid'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'openid' => 'Openid',
            'createtime' => 'Createtime',
            'return' => 'Return',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
