<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "qrcodeid".
 *
 * @property int $id
 * @property int $mappingid
 * @property int $type
 * @property int qrcodeid
 */
class Qrcodeid extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'qrcodeid';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mappingid', 'type','qrcodeid'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mappingid' => '映射ID',
            'type' => '类型',
            'qrcodeid'=>'二维码ID'
        ];
    }
    public function beforeSave($insert)
    {
        if(!$this->qrcodeid){
            $qrcodes=Qrcodeid::find()->select('qrcodeid')->column();
            $qrcodeid=1;
            while (in_array($qrcodeid,$qrcodes)){
                $qrcodeid++;
            }
            var_dump($qrcodeid);exit;
            $this->qrcodeid=$qrcodeid;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
