<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "question_reply".
 *
 * @property int $id
 * @property string $content 内容
 * @property int $createtime 时间
 * @property int $userid
 * @property int $is_doctor 是否医生回复
 */
class QuestionReply extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'question_reply';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['content','userid'], 'required'],
            [['id', 'createtime', 'userid', 'is_doctor','qid'], 'integer'],
            [['content'], 'string', 'max' => 500],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'content' => '内容',
            'createtime' => '时间',
            'userid' => '回复人',
            'is_doctor' => '是否医生回复',
        ];
    }
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->createtime = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
