<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "question".
 * 提问
 * @property int $id
 * @property int $userid
 * @property int $createtime
 * @property int $childid
 * @property int $doctirid
 * @property int $orderid
 */
class Question extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'question';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userid', 'createtime', 'childid', 'doctirid', 'orderid'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userid' => '用户',
            'createtime' => '创建时间',
            'childid' => '儿童id',
            'orderid' => '订单ID',
            'doctirid' => '医生ID（儿宝团队/专家）',
        ];
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->createtime = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * 创建提问
     * @param $orderid
     * @param $userid
     * @param $childid
     * @param $content
     * @param $tag
     * @return int
     */
    public static function Create($orderid, $userid, $childid, $content, $tag)
    {
        $order = Order::findOne(['orderid' => $orderid]);
        $question = new Question();
        $question->userid = $userid;
        $question->childid = $childid;
        $question->orderid = $order->id;
        if ($question->save()) {
            $quesInfo = new QuestionInfo();
            $quesInfo->content = $content;
            $quesInfo->qid = $question->id;
            $quesInfo->save();

            $quesTag = new QuestionTag();
            foreach ($tag as $k => $v) {
                $quesTag->qid = $question->id;
                $quesTag->tagid = $v;
                $quesTag->save();
            }

            $order = Order::findOne(['id' => $orderid]);
            if ($order) {
                $order->status = 2;
                $order->save();
            }
            return $question->id;
        }
        return 0;
    }
}
