<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "question".
 * 提问
 * @property int $id
 * @property int $userid
 * @property int $createtime
 * @property int $childid
 * @property int $doctorid
 * @property int $orderid
 * @property int $loginid
 */
class Question extends \yii\db\ActiveRecord
{
    public static $stateText=[0=>'未回复',1=>'已回复'];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'question';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userid', 'createtime', 'childid', 'doctorid', 'orderid','state','loginid'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userid' => '用户',
            'createtime' => '创建时间',
            'childid' => '儿童id',
            'orderid' => '订单ID',
            'doctorid' => '指定社区',
            'state'=>'回复状态',
        ];
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->createtime = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * 创建提问
     * @param $orderid
     * @param $userid
     * @param $childid
     * @param $content
     * @param $tag
     * @return int
     */
    public static function Create($userid, $content,$doctorid,$loginid)
    {
        $question = new Question();
        $question->userid = $userid;
        $question->doctorid=$doctorid;
        $question->loginid=$loginid;

        if ($question->save()) {
            $quesInfo = new QuestionInfo();
            $quesInfo->content = $content;
            $quesInfo->qid = $question->id;
            $quesInfo->save();

//            $quesTag = new QuestionTag();
//            foreach ($tag as $k => $v) {
//                $quesTag->qid = $question->id;
//                $quesTag->tagid = $v;
//                $quesTag->save();
//            }
//
//            $order = Order::findOne(['orderid' => $orderid]);
//            if ($order) {
//                $order->status = 2;
//                $order->save();
//            }
//            AskChatRoom::createRoom($order->id,$order->userid);

            return $question->id;
        }
        return 0;
    }
    /**
     *
     */
    public static function orderRow($orderid){
        $ques=self::findOne(['orderid'=>$orderid]);
        $tag=QuestionTag::find()->select('tagid')->where(['qid'=>$ques->id])->column();
        if($tag) {
            $tags = Tag::find()->select('name')->where(['in', 'id', $tag])->column();
        }
        $quesInfo=QuestionInfo::findOne(['qid'=>$ques->id]);
        $quesImg=QuestionImg::find()->select('image')->where(['qid'=>$ques->id])->column();

        return ['ques'=>$ques,'tag'=>implode('|',$tags),'content'=>$quesInfo->content,'images'=>$quesImg];
    }
}
