<?php

namespace common\models;

use common\helpers\SmsSend;
use Yii;

/**
 * This is the model class for table "user_notice".
 *
 * @property int $id 主键
 * @property int $type 通知类型
 * @property string $content
 * @property int $createtime
 * @property int $userid
 * @property int $touserid
 * @property int $method
 * @property int $phone
 */
class UserNotice extends \yii\db\ActiveRecord
{
    public static $typeText = [1 => '召回通知'];
    public static $contentText = [1 => '﻿家长您好，%s提醒您关注“儿宝宝”公众号，免费享受儿童中医健康指导等服务，还能查看到体检记录，步骤：微信搜索「儿宝宝 」公众号关注-点击育儿服务授权进入，如宝宝不显示，请手动添加宝宝即可，社区电话：%s'];
    public static $stateText = [1 => '成功', 0 => '失败'];
    public static $methodText = [1 => '短信', 2 => '微信公众号'];
    public static $methodTypeText = [1 => 1];//类型=》发送方式


    public static function setContent($args)
    {
        $query = array_shift($args);
        if (!self::$contentText[$query]) return false;
        array_unshift($args, self::$contentText[$query]);
        return call_user_func_array('sprintf', $args);
    }

    public function send($type = 1, $args = [])
    {
        $data = $args;
        array_unshift($data, $type);
        $this->content = self::setContent($data);
        $this->type = $type;
        $this->method = self::$methodTypeText[$type];
        if ($this->method == 1) {
            if (SmsSend::notice($args, $this->phone, 'SMS_152508191')) {
                $this->state = 1;
            }
        }
        $this->save();
        return $this->state;
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_notice';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['phone'], 'required'],
            [['type', 'createtime', 'userid', 'touserid', 'state', 'method', 'phone'], 'integer'],
            [['content'], 'string', 'max' => 200],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => '通知类型',
            'content' => '内容',
            'createtime' => '创建时间',
            'userid' => '发送人',
            'touserid' => '接收人',
            'state' => '发送状态',
            'method' => '发送方式',
            'phone' => '手机号'
        ];
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->createtime = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
