<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "user_to".
 *
 * @property int $id
 * @property int $userid
 * @property int $touserid
 * @property string $source
 * @property int $createtime
 */
class UserTo extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_to';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userid', 'touserid', 'createtime'], 'integer'],
            [['source'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userid' => 'Userid',
            'touserid' => 'Touserid',
            'source' => 'Source',
            'createtime' => 'Createtime',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
