<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property string $id
 * @property integer $phone
 * @property integer $level
 * @property integer $type
 * @property string $createtime
 */
class User extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            //[['phone'], 'required'],
            [['phone', 'level', 'type', 'createtime'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => '主键',
            'phone' => '手机号',
            'level' => '账号状态 -1后台删除 >0正常',
            'type' => '用户类型0 医生 1用户',
            'createtime' => '注册时间',
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id) {
        return static::findOne(['id' => $id, 'status' => 0]);
    }

    //通过id获取信息  刘方露
    public static function GetInfoById($id)
    {
        return self::find()->where(['id'=>$id])->one();
    }

    public function getParent()
    {
        return $this->hasOne(UserParent::className(),['userid'=>'id']);
    }
    public function beforeSave($insert)
    {
        if($insert && !$this->createtime)
        {
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getLogin(){

        return $this->hasOne(UserLogin::className(),['userid'=>'id']);

    }
    public function beforeDelete()
    {
        if($this->source=2)
        {
            $userP=UserParent::findOne(['userid'=>$this->id]);
            if($userP)
            {
                $userP->delete();
            }
            $child=ChildInfo::findOne(['userid'=>$this->id]);
            if($child)
            {
                $child->delete();
            }
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


}
