<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "wx_info".
 *
 * @property int $id
 * @property string $nickName
 * @property string $avatarUrl
 * @property string $city
 * @property string $province
 * @property string $country
 * @property string $language
 * @property int $gender
 * @property int $userid
 * @property int $loginid
 */
class WxInfo extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'wx_info';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['gender', 'userid', 'loginid'], 'integer'],
            [['nickName', 'city', 'province', 'country', 'language'], 'string', 'max' => 20],
            [['avatarUrl'], 'string', 'max' => 200],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nickName' => 'Nick Name',
            'avatarUrl' => 'Avatar Url',
            'city' => 'City',
            'province' => 'Province',
            'country' => 'Country',
            'language' => 'Language',
            'gender' => 'Gender',
            'userid' => 'Userid',
            'loginid' => 'Loginid',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
