<?php

namespace hospital\models\user;

use Yii;

/**
 * This is the model class for table "doctor_parent".
 *
 * @property integer $id
 * @property integer $doctorid
 * @property integer $parentid
 * @property integer $createtime
 * @property integer $level
 */
class DoctorParent extends \common\models\DoctorParent
{
    public  static function find()
    {
        $find=parent::find();
        $find->andFilterWhere(['not in','doctorid',[47118,39889,47156]]);
        if(\Yii::$app->user->identity->type != 1)
        {
            $doctorid=UserDoctor::findOne(['hospitalid'=>\Yii::$app->user->identity->hospital])->userid;
            return $find->andFilterWhere(['doctorid'=>$doctorid]); // TODO: Change the autogenerated stub
        }

        return $find;
    }
}
