<?php

namespace hospital\models\article;

use hospital\models\user\UserDoctor;
use Yii;

/**
 * This is the model class for table "article_user".
 *
 * @property string $id
 * @property string $childid
 * @property string $touserid
 * @property string $artid
 * @property string $createtime
 * @property string $userid
 */
class ArticleUser extends \common\models\ArticleUser
{
    public  static function find()
    {
        if(\Yii::$app->user->identity->type != 1)
        {
            $doctorid=UserDoctor::findOne(['hospitalid'=>\Yii::$app->user->identity->hospital])->userid;
            return parent::find()->andFilterWhere(['article_user.userid'=>$doctorid]); // TODO: Change the autogenerated stub
        }
        return parent::find();
    }
}
