<?php

namespace hospital\models\article;

use hospital\models\User;
use hospital\models\user\UserDoctor;
use Yii;

/**
 * This is the model class for table "article_info".
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property string $img
 * @property string $source
 */
class ArticleInfo extends \common\models\Article
{
   public function beforeSave($insert)
   {
       if(Yii::$app->user->identity->type !=1) {

           $hospital = Yii::$app->user->identity->hospital;
           $user=UserDoctor::findOne(['hospitalid'=>$hospital]);
           $userName=$user->name;
           $this->source=$userName;
       }
       return parent::beforeSave($insert); // TODO: Change the autogenerated stub
   }
}
