<?php

namespace databackend\models\message;

use Yii;

/**
 * This is the model class for table "message".
 *
 * @property integer $id
 * @property integer $type
 * @property integer $userid
 * @property integer $usertype
 * @property integer $createtime
 * @property string $content
 * @property string $url
 * @property string $title
 */
class Message extends \common\models\Message
{


    public function beforeSave($insert)
    {
        $this->userid=\Yii::$app->user->identity->hospital;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
