<?php

namespace databackend\models\article;

use databackend\models\user\UserDoctor;
use Yii;

/**
 * This is the model class for table "article".
 *
 * @property integer $id
 * @property integer $catid
 * @property integer $level
 * @property integer $createtime
 * @property integer $child_type
 * @property integer $num
 * @property integer $type
 * @property integer $source

 */
class Article extends \common\models\Article
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['child_type','type'], 'required'],
            [['subject','subject_pid','catid', 'level', 'createtime', 'child_type', 'num', 'type'], 'integer'],
        ];
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'catid' => '分类ID',
            'createtime' => '创建时间',
            'subject' => '子频道',
            'subject_pid' => '主频道',
            'child_type' => '针对儿童',
            'num' => '宣教次数',
            'type' => '文章类型',
        ];
    }

    public function beforeSave($insert)
    {
        $this->datauserid=\Yii::$app->user->identity->hospital;
        $this->datauserid=$this->datauserid?$this->datauserid:0;
        $this->source=UserDoctor::findOne(['hospitalid'=>\Yii::$app->user->identity->hospital])->name;
        if($insert)
        {
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
