<?php

/* @var $this yii\web\View */

$this->title = '中医儿童健康';
?>
<meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta name=apple-mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-status-bar-style content=black><meta name=format-detection content="telephone=no">
<script type=text/javascript src=/child-src/webim/webim.config.js></script><script type=text/javascript src=/child-src/webim/strophe-1.2.8.min.js></script>
<script>window.onresize = function () {
            var iWidth = document.documentElement.clientWidth;
            iWidth = iWidth > 414 ? 540 : iWidth;
            document.getElementsByTagName('html')[0].style.fontSize = iWidth / 23.4375 + 'px';
        }
        window.onresize();</script><link href=/child-src/css/app.1e6aeb4.css rel=stylesheet></head><body><div id=app></div><script>!function(e){function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}var r=window.webpackJsonp;window.webpackJsonp=function(t,c,a){for(var f,i,u,d=0,s=[];d<t.length;d++)i=t[d],o[i]&&s.push(o[i][0]),o[i]=0;for(f in c)Object.prototype.hasOwnProperty.call(c,f)&&(e[f]=c[f]);for(r&&r(t,c,a);s.length;)s.shift()();if(a)for(d=0;d<a.length;d++)u=n(n.s=a[d]);return u};var t={},o={32:0};n.e=function(e){function r(){f.onerror=f.onload=null,clearTimeout(i);var n=o[e];0!==n&&(n&&n[1](new Error("Loading chunk "+e+" failed.")),o[e]=void 0)}var t=o[e];if(0===t)return new Promise(function(e){e()});if(t)return t[2];var c=new Promise(function(n,r){t=o[e]=[n,r]});t[2]=c;var a=document.getElementsByTagName("head")[0],f=document.createElement("script");f.type="text/javascript",f.charset="utf-8",f.async=!0,f.timeout=12e4,n.nc&&f.setAttribute("nonce",n.nc),f.src=n.p+"child-src/js/"+e+"."+{0:"5058457",1:"5d032b7",2:"06bb62b",3:"d9cf7a2",4:"8ed1ae3",5:"f8d58b7",6:"b2231bb",7:"630c277",8:"4cd9bca",9:"72828bc",10:"42e0ea3",11:"62a3736",12:"085253d",13:"6ff7814",14:"4b7796a",15:"ebafc0f",16:"78229ff",17:"73329a2",18:"7ded757",19:"f2060a7",20:"24b7021",21:"858762e",22:"ec5c909",23:"de8a522",24:"287c690",25:"3ced64f",26:"3997e9f",27:"bb2fee5",28:"20cfc7f",29:"37c3b8d",30:"aad5e21",31:"cd21c41"}[e]+".js";var i=setTimeout(r,12e4);return f.onerror=f.onload=r,a.appendChild(f),c},n.m=e,n.c=t,n.i=function(e){return e},n.d=function(e,r,t){n.o(e,r)||Object.defineProperty(e,r,{configurable:!1,enumerable:!0,get:t})},n.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(r,"a",r),r},n.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},n.p="/",n.oe=function(e){throw console.error(e),e}}([]);</script><script type=text/javascript src=/child-src/js/vendor.aad5e21.js></script><script type=text/javascript src=/child-src/js/app.cd21c41.js></script>