<?php
/**
 * 全局控制器
 * User: wangzhen
 * Date: 2017/12/6
 * Time: 下午2:05
 */

namespace api\controllers;


use common\components\Code;
use common\models\User;
use common\models\UserInfo;
use common\models\UserLogin;
use yii\base\ActionEvent;
use yii\helpers\ArrayHelper;
use yii\web\Response;

class Controller extends \yii\web\Controller
{
    private $result = [];
    protected $userid = 0;
    protected $user;
    protected $seaver_token;
    protected $appToken;
    protected $hxusername;

    public function beforeAction($action)
    {
        \Yii::$app->response->format=Response::FORMAT_JSON;

        $this->seaver_token=\Yii::$app->request->headers->get('sessionkey');
        $this->hxusername=\Yii::$app->request->headers->get('hxusername');

        $cache=\Yii::$app->rdmp;
        $session=$cache->get($this->seaver_token);
        $session=explode('@@',$session);

        if($this->seaver_token && $session[0])
        {
            $userLogin=UserLogin::findOne(['xopenid'=>$session[0]]);
            if(!$userLogin){
                $cache=\Yii::$app->rdmp;
                $session=$cache->lpush("user_login_error",$session[0]);
            }
            $this->userid=$userLogin->userid;
            $this->user=$userLogin->user;
            $this->appToken=$session;
        }


        /*
        if(!$seaver_token)
        {
            \Yii::$app->response->data = ['code' => 30001,'msg' => '数字签证错误'];
            return false;
        }*/

        //预留，判断签名是否正确

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function afterAction($action, $result)
    {
        $return = parent::afterAction($action, $result); // TODO: Change the autogenerated

        $return=$this->return_array_filter($return);
        if($result instanceof Code && $result->getCode())
        {
            return $result->getCode();
        }

        $this->result=Code::result();
        if (!isset($return['data']) && $return) {
            $this->result['data'] = $return;
        }elseif (is_array($return)) {
            if($return) {
                foreach ($return as $k => $v) {
                    if ($k == 'data' || $k == 'msg' || $k == 'code') {
                        $this->result[$k] = $v;
                    } else {
                        $this->result['data'][$k] = $v;
                    }
                }
            }else{
                $this->result['data'] = [];
            }
        } else {
            if (!isset($this->result['data'])) unset($this->result['data']);
        }
        return $this->result;
    }

    private function return_array_filter($return)
    {
        if(!is_array($return)) return $return;
        $data=[];
        foreach($return as $k=>$v)
        {
            if(is_array($v))
            {
                $row=$this->return_array_filter($v);
            }else{
                $row= $v===null?"":$v;
            }
            $data[$k]=$row;
        }
        return $data;
    }

}