<?php
namespace backend\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;

/**
 * ArticleSearchModel represents the model behind the search form about `app\models\article\Article`.
 */
class ArticleSearchModel extends Article
{
    public $title;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'catid', 'level', 'createtime', 'child_type', 'num', 'type','subject_pid','subject'], 'integer'],
            [['title'],'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }
    public function attributeLabels()
    {
        $return=parent::attributeLabels(); // TODO: Change the autogenerated stub
        $return['title']='标题';
        return $return;
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Article::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'catid' => $this->catid,
            'level' => $this->level,
            'createtime' => $this->createtime,
            'child_type' => $this->child_type,
            'subject_pid'=>$this->subject_pid,
            'subject'=>$this->subject,
            'num' => $this->num,
            'type' => $this->type,
        ]);

        if($this->title){
            $query->leftJoin('article_info', '`article_info`.`id` = `article`.`id`');
            $query->andWhere(['like','title',$this->title]);

        }
        $query->orderBy([self::primaryKey()[0]=>SORT_DESC]);
        //echo $query->createCommand()->getRawSql();
        return $dataProvider;
    }
}
