<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "auto_user".
 *
 * @property int $id
 * @property string $username 用户名
 * @property string $password 密码
 * @property int $createtime 添加时间
 * @property int $lasttime 最后一次登录时间
 * @property string $auth_key
 * @property string $accessToken
 */
class AutoUser extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'auto_user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password'], 'required'],
            [['createtime', 'lasttime'], 'integer'],
            [['username'], 'string', 'max' => 255],
            [['password', 'auth_key', 'accessToken'], 'string', 'max' => 32],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => '用户名',
            'password' => '密码',
            'createtime' => '添加时间',
            'lasttime' => '最后一次登录时间',
            'auth_key' => 'Auth Key',
            'accessToken' => 'Access Token',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert)
        {
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
