<?php
/**
 * Created by PhpStorm.
 * User: wangzhen
 * Date: 2018/9/4
 * Time: 下午5:35
 */

namespace api\models;


use common\models\ArticleSend;

class ChildInfo extends \common\models\ChildInfo
{
    public function beforeSave($insert)
    {
        $return= parent::beforeSave($insert); // TODO: Change the autogenerated stub

        if($insert){
            //发送最近宣教文章
            $articleSend = new ArticleSend();
            //$articleSend->artid=$av;
            $articleSend->childs[] = $this;
            $articleSend->type = $this->getType(1);
            $articleSend->doctorid = $this->doctorid;
            $articleSend->send('addChild', false);
        }

    }

}