<?php

namespace databackend\models;

use Yii;

/**
 * This is the model class for table "doctor_parent".
 *
 * @property integer $id
 * @property integer $doctorid
 * @property integer $parentid
 * @property integer $createtime
 * @property integer $level
 */
class UserDoctor extends \common\models\UserDoctor
{
    public  static function find()
    {
        $find=parent::find();
    
        return $find->andFilterWhere(['is_guanfang'=>0]); // TODO: Change the autogenerated stub
    }
}
